Brand = {}
	Brand[1] = {}
	Brand[2] = {}
	Brand[3] = {}
	Brand[4] = {}
	Brand[5] = {}
	Brand[6] = {}
	Brand[7] = {}
	Brand[8] = {}

	Brand[1].Name = "AMD"
	Brand[1].rn = "AMD"
	Brand[2].Name = "NVIDIA"
	Brand[2].rn = "NVDA"
	Brand[3].Name = "INTEL"
	Brand[3].rn = "INTC"
	Brand[4].Name = "Netflix"
	Brand[4].rn = "NFLX"
	Brand[5].Name = "Apple"
	Brand[5].rn = "AAPL"
	Brand[6].Name = "Facebook"
	Brand[6].rn = "Facebook"
	Brand[7].Name = "Microsoft"
	Brand[7].rn = "MSFT"
	Brand[8].Name = "Google"
	Brand[8].rn = "GOOGL"


	Sectors = {}
	Sectors[1] = "Banques"
	Sectors[2] = "Assurances"
	Sectors[3] = "Chemins de Fer"
	Sectors[4] = "Canaux"
	Sectors[5] = "Foncier et Immo."
	Sectors[6] = "Houillères"
	Sectors[7] = "Mines"
	Sectors[8] = "Forges"
	Sectors[9] = "Métaux"
	Sectors[10] = "Gaz"
	Sectors[11] = "Chimie"
	Sectors[12] = "Docks"
	Sectors[13] = "Eaux"
	Sectors[14] = "Navigation"
	Sectors[15] = "Filatures"
	Sectors[16] = "Transports"
	Sectors[17] = "Electricité"
	Sectors[18] = "Matériel"
	Sectors[19] = "Alimentation"
	Sectors[20] = "Constr. Navales"
	Sectors[21] = "Matériaux"
	Sectors[22] = "Constr. Mécaniques"
	Sectors[23] = "Imprimeries"
	Sectors[24] = "Magasins"
