	title = love.graphics.newFont("ressources/Ubuntu-B.ttf", 27)
	subtitle = love.graphics.newFont("ressources/Ubuntu-B.ttf",23)
	other_text = love.graphics.newFont("ressources/FuturaExtended.ttf", 18)
	date_box_text1 = love.graphics.newFont("ressources/segoe.ttf", 18)
	graphfont = love.graphics.newFont(12)